// Customer OTP — phone-based sign-in for the portal.
//
// Foundation phase contract: SMS is not yet wired. Codes are emitted via
// console.info so they appear in Vercel logs / local dev; the universal
// test code "123456" is also accepted so QA flows work without a phone.
// A future phase plugs in a real SMS provider (Twilio / a Thai aggregator)
// behind `sendOtpViaSms` while keeping the issue / verify contract the
// same.
//
// Codes are stored hashed (sha256(salt || code)) so the table never holds
// the plaintext. Salt is the row id itself, generated by the DB.
//
// Security limits:
//   • 6-digit numeric codes.
//   • 5-minute TTL.
//   • One active code per phone — newer codes invalidate older ones.
//   • 5 verify attempts per code; after that the code is dead even if
//     a valid one is sent through.
//
// Server-only.

import crypto from "node:crypto";
import { getSupabaseAdmin } from "@/lib/supabaseAdmin";
import { normalizePhone } from "@/lib/phone";
import { sendSms } from "@/lib/smsProvider";

const TTL_SECONDS = 5 * 60;
const MAX_ATTEMPTS = 5;
const UNIVERSAL_DEV_CODE = "123456";

function hashCode(salt: string, code: string): string {
  return crypto
    .createHash("sha256")
    .update(`${salt}::${code}`)
    .digest("hex");
}

/** 6-digit zero-padded random code. */
function generateCode(): string {
  const n = crypto.randomInt(0, 1_000_000);
  return String(n).padStart(6, "0");
}

export type IssueResult =
  | { ok: true; requestId: string; expiresAt: string; devCode: string | null }
  | { ok: false; reason: string };

/**
 * Generate + persist a code for the given phone. Invalidates any previous
 * un-consumed codes for the same phone (by setting consumed_at=now on
 * them) so only the freshest is verifiable.
 */
export async function issueCustomerOtp(
  rawPhone: string,
  meta: Record<string, unknown> = {}
): Promise<IssueResult> {
  const phone = normalizePhone(rawPhone);
  if (!phone) {
    return { ok: false, reason: "เบอร์โทรไม่ถูกต้อง" };
  }
  const admin = getSupabaseAdmin();
  if (!admin) {
    return { ok: false, reason: "SERVICE_ROLE_KEY ยังไม่ตั้งค่า" };
  }

  // Invalidate older un-consumed codes for this phone so a fresh issue
  // is the only valid one going forward.
  await admin
    .from("customer_otp_codes")
    .update({ consumed_at: new Date().toISOString() })
    .eq("phone", phone)
    .is("consumed_at", null);

  const code = generateCode();
  const expiresAt = new Date(Date.now() + TTL_SECONDS * 1000).toISOString();

  const insertRes = await admin
    .from("customer_otp_codes")
    .insert({
      phone,
      // Placeholder hash; we re-update with the row.id-as-salt below.
      code_hash: "pending",
      expires_at: expiresAt,
      request_meta: meta,
    })
    .select("id")
    .single();
  if (insertRes.error || !insertRes.data) {
    return {
      ok: false,
      reason: insertRes.error?.message ?? "Insert failed",
    };
  }
  const rowId = (insertRes.data as { id: string }).id;
  const hash = hashCode(rowId, code);
  await admin
    .from("customer_otp_codes")
    .update({ code_hash: hash })
    .eq("id", rowId);

  // Hand off to the SMS provider. The Console impl (default) keeps the
  // existing log-only behaviour; configured providers (Twilio, future
  // aggregators) deliver to the actual phone. Fire-and-forget — a
  // provider outage NEVER blocks the OTP from being issuable; the dev
  // code path + log line is the fallback.
  void sendSms({
    to: phone,
    body: `Care U OPS รหัสยืนยัน: ${code} (อายุ 5 นาที)`,
    meta: { otpRequestId: rowId, kind: "customer-otp" },
  }).catch((err) => {
    console.warn(
      "[customer-otp] sms send threw",
      err instanceof Error ? err.message : String(err)
    );
  });

  return {
    ok: true,
    requestId: rowId,
    expiresAt,
    // Surface the dev code in non-production so QA flows work without
    // a phone. NEVER returned in production.
    devCode: process.env.NODE_ENV === "production" ? null : code,
  };
}

export type VerifyResult =
  | {
      ok: true;
      phone: string;
      /** Profile-lookup is the route handler's job; we only return phone. */
    }
  | { ok: false; reason: string; attemptsLeft?: number };

/**
 * Verify a customer-supplied code against the most recent un-consumed
 * row for the phone. Returns ok=true exactly once per code; subsequent
 * attempts return "already used".
 *
 * Accepts the universal dev code `123456` when NODE_ENV != production —
 * critical for QA flows since SMS isn't wired.
 */
export async function verifyCustomerOtp(
  rawPhone: string,
  code: string
): Promise<VerifyResult> {
  const phone = normalizePhone(rawPhone);
  if (!phone) {
    return { ok: false, reason: "เบอร์โทรไม่ถูกต้อง" };
  }
  if (!/^\d{6}$/.test(code)) {
    return { ok: false, reason: "รหัสต้องเป็นเลข 6 หลัก" };
  }
  const admin = getSupabaseAdmin();
  if (!admin) {
    return { ok: false, reason: "SERVICE_ROLE_KEY ยังไม่ตั้งค่า" };
  }

  // Dev-mode shortcut. Still has to land on an existing record so the
  // attempt is auditable.
  const isDev = process.env.NODE_ENV !== "production";

  const fetch = await admin
    .from("customer_otp_codes")
    .select("id, code_hash, expires_at, consumed_at, attempts")
    .eq("phone", phone)
    .is("consumed_at", null)
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle();
  if (fetch.error || !fetch.data) {
    return { ok: false, reason: "ไม่พบรหัสที่ออกให้ — กรุณาขอใหม่" };
  }
  const row = fetch.data as {
    id: string;
    code_hash: string;
    expires_at: string;
    consumed_at: string | null;
    attempts: number;
  };
  if (new Date(row.expires_at).getTime() < Date.now()) {
    await admin
      .from("customer_otp_codes")
      .update({ consumed_at: new Date().toISOString() })
      .eq("id", row.id);
    return { ok: false, reason: "รหัสหมดอายุ — กรุณาขอใหม่" };
  }
  if (row.attempts >= MAX_ATTEMPTS) {
    await admin
      .from("customer_otp_codes")
      .update({ consumed_at: new Date().toISOString() })
      .eq("id", row.id);
    return { ok: false, reason: "ใส่รหัสผิดเกินกำหนด — กรุณาขอใหม่" };
  }

  const expectedHash = hashCode(row.id, code);
  const acceptDev = isDev && code === UNIVERSAL_DEV_CODE;
  const acceptReal = expectedHash === row.code_hash;
  if (!acceptDev && !acceptReal) {
    const nextAttempts = row.attempts + 1;
    await admin
      .from("customer_otp_codes")
      .update({ attempts: nextAttempts })
      .eq("id", row.id);
    return {
      ok: false,
      reason: "รหัสไม่ถูกต้อง",
      attemptsLeft: Math.max(0, MAX_ATTEMPTS - nextAttempts),
    };
  }

  await admin
    .from("customer_otp_codes")
    .update({
      consumed_at: new Date().toISOString(),
      attempts: row.attempts + 1,
    })
    .eq("id", row.id);

  return { ok: true, phone };
}
