-- Communications maturity — delivery state + resend audit + transcode
-- queue.
--
-- This migration upgrades customer_notifications from "send queued" to
-- "delivery-aware operational messaging". Four sets of changes:
--
--   1. Expanded status enum on customer_notifications:
--        + 'delivered'  — provider confirmed delivery (Twilio webhook)
--        + 'dead_letter' — gave up; outside the retry loop
--        + 'cancelled'  — operator cancelled before send
--      Existing values ('queued','sending','sent','failed','skipped')
--      keep their meaning so the worker + queue UI continue to work.
--
--   2. New columns on customer_notifications:
--        • delivered_at         — when the provider confirmed delivery
--        • provider_message_id  — Twilio SID / LINE request id
--        • last_provider_status — raw vendor status string
--        • cancelled_at         — operator cancel timestamp
--        • cancelled_by         — operator profile id
--        • resent_from          — original notification id when this row
--                                 was created by a resend action
--
--   3. New tables:
--        • public.notification_resend_log — append-only audit of every
--          resend / cancel action with operator + reason.
--        • public.media_transcode_queue — list of upload paths that
--          still need server-side normalization (HEIC → JPEG +
--          orientation fix). Drained by /api/cron/heic-transcode.
--
--   4. Index hygiene to support the new query patterns:
--        • pending index extended to also exclude 'cancelled' /
--          'dead_letter' rows.
--        • per-customer rate-limit lookups by (customer_id, channel,
--          created_at) — the dispatch worker uses this for the new
--          per-customer caps.
--
-- Idempotent + additive. Existing data untouched.

create extension if not exists "pgcrypto";

-- ---------- 1. expanded status enum on customer_notifications ------------
--
-- The existing CHECK constraint name is unknown (auto-generated by the
-- inline CHECK in `20260535`). We use a DO block to find + drop the
-- constraint, then add the new one. NOT VALID semantics — we won't
-- re-check existing rows.

do $$
declare
  v_constraint_name text;
begin
  select conname into v_constraint_name
  from pg_constraint
  where conrelid = 'public.customer_notifications'::regclass
    and contype  = 'c'
    and conname  like '%status%';
  if v_constraint_name is not null then
    execute format(
      'alter table public.customer_notifications drop constraint %I',
      v_constraint_name
    );
  end if;
exception when undefined_table then
  null;
end $$;

do $$
begin
  alter table public.customer_notifications
    add constraint customer_notifications_status_check
    check (status in (
      'queued',
      'sending',
      'sent',
      'delivered',
      'failed',
      'dead_letter',
      'skipped',
      'cancelled'
    ))
    not valid;
exception when undefined_table then
  null;
end $$;

-- ---------- 2. customer_notifications column additions -------------------

alter table public.customer_notifications
  add column if not exists delivered_at         timestamptz,
  add column if not exists provider_message_id  text,
  add column if not exists last_provider_status text,
  add column if not exists cancelled_at         timestamptz,
  add column if not exists cancelled_by         uuid,
  add column if not exists resent_from          uuid references public.customer_notifications(id) on delete set null;

-- Drop the old pending index, recreate with the expanded "active" set
-- so the worker doesn't scan cancelled / dead_letter rows.
drop index if exists public.customer_notifications_pending_idx;
create index if not exists customer_notifications_pending_idx
  on public.customer_notifications (status, send_after)
  where status in ('queued','sending');

-- Per-customer rate-limit lookups — the dispatch worker queries by
-- (customer_id, channel, created_at) to enforce the new per-customer
-- caps. Index covers SMS + LINE since both are rate-limited.
create index if not exists customer_notifications_customer_channel_idx
  on public.customer_notifications (customer_id, channel, created_at desc)
  where customer_id is not null;

-- Per-order rate-limit lookups (the worker keys on payload->>'orderId').
-- We can't easily index a JSONB expression without IMMUTABLE casts,
-- but the dedup query already exists from 20260537. Skip.

-- Provider-message-id lookups — the Twilio webhook joins by
-- provider_message_id to find the notification row. Sparse index so
-- it only covers rows that have actually been dispatched.
create index if not exists customer_notifications_provider_msg_idx
  on public.customer_notifications (provider_message_id)
  where provider_message_id is not null;

-- Delivered timeline lookups — the customer portal activity feed
-- queries by delivered_at to surface "delivered to your phone".
create index if not exists customer_notifications_delivered_idx
  on public.customer_notifications (customer_id, delivered_at desc)
  where delivered_at is not null;

-- ---------- 3. notification_resend_log -----------------------------------
--
-- Append-only audit of every resend / cancel / dead-letter-retry
-- action. The /admin/dispatch + /admin/customers/[id] UIs surface
-- this so operators can see who clicked "resend" and why.

create table if not exists public.notification_resend_log (
  id                  uuid primary key default gen_random_uuid(),
  /** Original notification row that was resent / cancelled. */
  notification_id     uuid references public.customer_notifications(id) on delete set null,
  /** When the action created a new queue row (resend), this points at it. */
  new_notification_id uuid references public.customer_notifications(id) on delete set null,
  /** 'resend' | 'cancel' | 'dead_letter_retry' */
  action              text not null check (action in ('resend','cancel','dead_letter_retry')),
  /** Operator who clicked the button. */
  actor_id            uuid,
  /** Operator-supplied free-text reason (optional but encouraged). */
  reason              text,
  /** IP captured at action time for the audit trail. */
  request_ip          text,
  customer_id         uuid references public.customers(id) on delete set null,
  branch_id           text,
  created_at          timestamptz not null default now()
);

create index if not exists notification_resend_log_notification_idx
  on public.notification_resend_log (notification_id);
create index if not exists notification_resend_log_customer_idx
  on public.notification_resend_log (customer_id, created_at desc)
  where customer_id is not null;
create index if not exists notification_resend_log_created_idx
  on public.notification_resend_log (created_at desc);

alter table public.notification_resend_log enable row level security;

drop policy if exists notification_resend_log_admin_read
  on public.notification_resend_log;
create policy notification_resend_log_admin_read
  on public.notification_resend_log
  for select to authenticated
  using (public.current_user_role() in ('owner','hq_admin'));

drop policy if exists notification_resend_log_branch_read
  on public.notification_resend_log;
create policy notification_resend_log_branch_read
  on public.notification_resend_log
  for select to authenticated
  using (
    public.current_user_role() in ('branch_manager','front_staff')
    and (branch_id is null or branch_id = public.current_user_branch_code())
  );

-- ---------- 4. media_transcode_queue -------------------------------------
--
-- The portal upload pipeline (lib/uploadClient.ts) tags HEIC bytes
-- that the browser couldn't decode with needsTranscoding=true. The
-- upload route inserts a row here; /api/cron/heic-transcode drains
-- the queue, calls the transcoder, and writes the transcoded path
-- back so the gallery can render it.
--
-- The actual transcoder library (sharp + libheif, or a Supabase
-- Edge Function with libvips) is wired by the cron route; this table
-- is the contract between "upload happens" and "conversion happens".

create table if not exists public.media_transcode_queue (
  id              uuid primary key default gen_random_uuid(),
  /** Storage path of the source object — the HEIC / HEIF bytes the
   *  client uploaded. */
  source_path     text not null,
  /** Storage path of the transcoded output. Set when status=done. */
  output_path     text,
  /** Source MIME (image/heic | image/heif | …). */
  source_mime     text not null,
  /** What we're doing: 'transcode' (full HEIC → JPEG normalisation)
   *  or 'thumbnail' (smaller version next to an existing JPEG). */
  operation       text not null default 'transcode'
                  check (operation in ('transcode','thumbnail','orientation_fix')),
  status          text not null default 'pending'
                  check (status in ('pending','processing','done','failed','dead_letter')),
  attempts        integer not null default 0,
  error_reason    text,
  /** Customer / order back-references — null on quote-flow uploads
   *  where the customer isn't yet known. */
  customer_id     uuid references public.customers(id) on delete set null,
  order_id        uuid references public.orders(id) on delete set null,
  branch_id       text,
  created_at      timestamptz not null default now(),
  processed_at    timestamptz
);

create index if not exists media_transcode_queue_pending_idx
  on public.media_transcode_queue (status, created_at)
  where status in ('pending','processing');
create index if not exists media_transcode_queue_source_idx
  on public.media_transcode_queue (source_path);

alter table public.media_transcode_queue enable row level security;

drop policy if exists media_transcode_queue_admin_read
  on public.media_transcode_queue;
create policy media_transcode_queue_admin_read
  on public.media_transcode_queue
  for select to authenticated
  using (public.current_user_role() in ('owner','hq_admin'));

-- ---------- 5. customer_activity activity-kind comment ------------------
--
-- New activity kinds the timeline expansion writers will use:
--   • notification_delivered  — provider confirmed delivery
--   • notification_failed     — provider said failed/undelivered
--   • notification_resent     — operator clicked "resend"
--   • notification_cancelled  — operator clicked "cancel"
--
-- customer_activity.kind is free-form text so no migration is needed,
-- but documenting here so future readers can grep.

-- ============================================================================
-- Verification queries:
--
--   select status, count(*) from public.customer_notifications group by status;
--   select count(*) from public.notification_resend_log;        -- 0
--   select count(*) from public.media_transcode_queue;          -- 0
--   select indexname from pg_indexes
--     where schemaname='public'
--       and tablename in ('customer_notifications','notification_resend_log','media_transcode_queue')
--   order by indexname;
--
-- ============================================================================
